In [1]:
import pandas as pd

In [14]:
disruptions_2023 = pd.read_csv('disruptions-2023.csv')
services_2023 = pd.read_csv('services-2023.csv')

In [19]:
def_data = pd.read_csv('definitive_df.csv')

In [20]:
def_data

,RDT-ID,Trajectory,Date,Day of the Week,Maximum Delay,Arrival Delay of Last Stop (min),Nr. of Planned Stops,Nr. of Cancelled Arrivals,Nr. of Cancelled Departures,Nr. of Delayed Arrivals,Nr. of Delayed Departures,Partly Cancelled,Completely Cancelled,Last Arrival Cancelled
0,[738804],Rotterdam Centraal - Utrecht Centraal,2019-01-01,Tuesday,1,0.0,5,0,0,2,2,False,False,False
1,[738805],Utrecht Centraal - Rotterdam Centraal,2019-01-01,Tuesday,2,0.0,6,0,0,2,1,False,False,False
2,[738806],Rotterdam Centraal - Utrecht Centraal,2019-01-01,Tuesday,2,0.0,5,0,0,2,2,False,False,False
3,[738807],Utrecht Centraal - Rotterdam Centraal,2019-01-01,Tuesday,2,2.0,5,0,0,2,0,False,False,False
4,[738808],Rotterdam Centraal - Utrecht Centraal,2019-01-01,Tuesday,1,0.0,5,0,0,0,2,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9240682,[15100115],Enschede - Den Haag Centraal,2024-12-31,Tuesday,6,4.0,7,5,5,2,3,True,False,False
9240683,[15100584],Groningen - Den Haag Centraal,2024-12-31,Tuesday,2,2.0,5,2,2,1,0,True,False,False
9240684,[15100940],Heerlen - Enkhuizen,2024-12-31,Tuesday,6,0.0,14,4,4,2,1,True,False,False
9240685,[15101612],Amsterdam Sloterdijk - Amsterdam Centraal,2024-12-31,Tuesday,1,0.0,0,False,False,0,1,False,False,False
9240686,[15101626],Amsterdam Centraal - Hoorn,2024-12-31,Tuesday,1,0.0,17,14,14,0,1,True,False,False

In [6]:
disruptions_2023

,rdt_id,ns_lines,rdt_lines,rdt_lines_id,rdt_station_names,rdt_station_codes,cause_nl,cause_en,statistical_cause_nl,statistical_cause_en,cause_group,start_time,end_time,duration_minutes
0,45999,Amsterdam-Rotterdam-Brussel (HSL),"Amsterdam Centraal - Schiphol Airport, Rotterd...","24,32","Amsterdam Centraal,Amsterdam Lelylaan,Amsterda...","ASD, ASDL, ASS, RTD, SHL",wisselstoring,points failure,wisselstoring,points failure,infrastructure,2023-01-01 08:19:26,2023-01-01 22:43:08,864.0
1,46000,Zwolle-Leeuwarden,Leeuwarden - Zwolle,160,"Heerenveen,Wolvega,Heerenveen IJsstadion","HR, WV, HRY",dier op het spoor,an animal on the railway track,dier op het spoor,an animal on the railway track,external,2023-01-01 10:31:49,2023-01-01 10:56:17,24.0
2,46001,Heerlen-Aachen Hbf,Aachen Hbf - Heerlen,130,"Aachen Hbf,Eygelshoven Markt,Heerlen,Heerlen D...","AHBF, EGHM, HRL, HRLK, HZ, LG, AW",beperkingen in de materieelinzet,problems with the rolling stock,beperkingen in de materieelinzet,problems with the rolling stock,rolling stock,2023-01-01 13:19:24,2023-01-02 00:02:39,643.0
3,46002,Zutphen-Winterswijk,Winterswijk - Zutphen,83,"Vorden,Zutphen","VD, ZP",aanrijding,collision,aanrijding,collision,accidents,2023-01-01 17:15:22,2023-01-01 20:14:23,179.0
4,46003,Heerlen-Aachen Hbf,Aachen Hbf - Heerlen,130,"Aachen Hbf,Eygelshoven Markt,Heerlen,Heerlen D...","AHBF, EGHM, HRL, HRLK, HZ, LG, AW",beperkingen in de materieelinzet,problems with the rolling stock,beperkingen in de materieelinzet,problems with the rolling stock,rolling stock,2023-01-02 05:57:27,2023-01-03 02:07:13,1210.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5163,51162,Amsterdam-Utrecht,Amsterdam Centraal - Utrecht Centraal,136,"Abcoude,Amsterdam Amstel,Amsterdam Bijlmer Are...","AC, ASA, ASB, ASD, ASDM, ASHD, BKL, DVD, MAS",defecte trein,broken down train,defecte trein,broken down train,rolling stock,2023-12-21 07:39:46,2023-12-21 09:02:01,82.0
5164,51163,Almere-Lelystad,"Almere Oostvaarders - Utrecht Centraal, Amster...","144,145,149","Almere Centrum,Almere Buiten,Almere Oostvaarde...","ALM, ALMB, ALMO, ALMP, LLS",defecte trein,broken down train,defecte trein,broken down train,rolling stock,2023-12-21 07:51:47,2023-12-21 07:58:33,7.0
5165,51164,Arnhem-Duisburg-Düsseldorf,"Arnhem Centraal - Basel SBB, Arnhem Centraal -...","129,178,179","Arnhem Centraal,Arnhem Velperpoort,Duiven,Emme...","AH, AHP, DVN, EM, ZV, WTV, EL",wisselstoring,points failure,wisselstoring,points failure,infrastructure,2023-12-21 09:56:39,NaN,NaN
5166,51165,Meppel-Leeuwarden,Leeuwarden - Zwolle,160,"Akkrum,Grou-Jirnsum,Heerenveen,Leeuwarden,Mepp...","AKM, GW, HR, LW, MP, SWK, WV, HRY",sein- en wisselstoring,signalling and points failure,sein- en wisselstoring,signalling and points failure,infrastructure,2023-12-21 10:58:26,2023-12-21 11:58:14,60.0
5167,51166,Arnhem-Nijmegen; Arnhem-Nijmegen; Arnhem-Tiel,"Arnhem Centraal - Nijmegen, Arnhem Centraal - ...","54,59","Arnhem Centraal,Arnhem Zuid,Elst,Hemmen-Dodewa...","AH, AHZ, EST, HMN, KTR, NM, NML, OP, TL, ZA",defecte trein,broken down train,defecte trein,broken down train,rolling stock,2023-12-21 11:15:15,2023-12-21 11:39:02,24.0

In [23]:
filtered_disruptions = disruptions_2023[['rdt_lines', 'statistical_cause_en', 'start_time', 'end_time']]
filtered_disruptions = filtered_disruptions.assign(rdt_lines=filtered_disruptions['rdt_lines'].str.split(',')).explode('rdt_lines')
filtered_disruptions

,rdt_lines,statistical_cause_en,start_time,end_time
0,Amsterdam Centraal - Schiphol Airport,points failure,2023-01-01 08:19:26,2023-01-01 22:43:08
0,Rotterdam Centraal - Schiphol Airport (HSL),points failure,2023-01-01 08:19:26,2023-01-01 22:43:08
1,Leeuwarden - Zwolle,an animal on the railway track,2023-01-01 10:31:49,2023-01-01 10:56:17
2,Aachen Hbf - Heerlen,problems with the rolling stock,2023-01-01 13:19:24,2023-01-02 00:02:39
3,Winterswijk - Zutphen,collision,2023-01-01 17:15:22,2023-01-01 20:14:23
...,...,...,...,...
5165,Arnhem Centraal - Düsseldorf Hbf,points failure,2023-12-21 09:56:39,NaN
5165,Arnhem Centraal - Frankfurt (M) Hbf,points failure,2023-12-21 09:56:39,NaN
5166,Leeuwarden - Zwolle,signalling and points failure,2023-12-21 10:58:26,2023-12-21 11:58:14
5167,Arnhem Centraal - Nijmegen,broken down train,2023-12-21 11:15:15,2023-12-21 11:39:02
5167,Arnhem Centraal - Tiel,broken down train,2023-12-21 11:15:15,2023-12-21 11:39:02

In [35]:
# Convert start_time to datetime
filtered_disruptions['start_time'] = pd.to_datetime(filtered_disruptions['start_time'])

# Extract the date from start_time
filtered_disruptions['date'] = filtered_disruptions['start_time'].dt.date

# Group by date and rdt_lines, and aggregate the statistical causes into a list
daily_disruptions = filtered_disruptions.groupby(['date', 'rdt_lines'])['statistical_cause_en'].apply(list).reset_index()

# Rename columns for clarity
daily_disruptions.columns = ['Date', 'Trajectory', 'Statistical Causes']

daily_disruptions

,Date,Trajectory,Statistical Causes
0,2023-01-01,Rotterdam Centraal - Schiphol Airport (HSL),[points failure]
1,2023-01-01,Aachen Hbf - Heerlen,[problems with the rolling stock]
2,2023-01-01,Amsterdam Centraal - Schiphol Airport,[points failure]
3,2023-01-01,Leeuwarden - Zwolle,[an animal on the railway track]
4,2023-01-01,Winterswijk - Zutphen,[collision]
...,...,...,...
6938,2023-12-21,Berlin Ostbahnhof - Hengelo,[staffing problems]
6939,2023-12-21,Den Haag HS - Rotterdam Centraal,[points failure]
6940,2023-12-21,Leeuwarden - Zwolle,[signalling and points failure]
6941,2023-12-21,Leiden Centraal - Utrecht Centraal,[broken down train]
6942,2023-12-21,Rotterdam Centraal - Schiphol Airport (HSL),[disruption elsewhere]

In [37]:
# Add a column for the number of disruptions
daily_disruptions['Disruption Count'] = daily_disruptions['Statistical Causes'].apply(len)

daily_disruptions

,Date,Trajectory,Statistical Causes,Disruption Count
0,2023-01-01,Rotterdam Centraal - Schiphol Airport (HSL),[points failure],1
1,2023-01-01,Aachen Hbf - Heerlen,[problems with the rolling stock],1
2,2023-01-01,Amsterdam Centraal - Schiphol Airport,[points failure],1
3,2023-01-01,Leeuwarden - Zwolle,[an animal on the railway track],1
4,2023-01-01,Winterswijk - Zutphen,[collision],1
...,...,...,...,...
6938,2023-12-21,Berlin Ostbahnhof - Hengelo,[staffing problems],1
6939,2023-12-21,Den Haag HS - Rotterdam Centraal,[points failure],1
6940,2023-12-21,Leeuwarden - Zwolle,[signalling and points failure],1
6941,2023-12-21,Leiden Centraal - Utrecht Centraal,[broken down train],1
6942,2023-12-21,Rotterdam Centraal - Schiphol Airport (HSL),[disruption elsewhere],1

In [38]:
# Filter def_data for all trajectories in 2023
def_data['Date'] = pd.to_datetime(def_data['Date'])
def_data_2023 = def_data[def_data['Date'].dt.year == 2023]

# Convert 'Date' column in daily_disruptions to datetime
daily_disruptions['Date'] = pd.to_datetime(daily_disruptions['Date'])

# Merge with daily_disruptions on Trajectory and Date
merged_data = pd.merge(def_data_2023, daily_disruptions, left_on=['Trajectory', 'Date'], right_on=['Trajectory', 'Date'], how='left')

merged_data[merged_data['Statistical Causes'].notnull()]

,RDT-ID,Trajectory,Date,Day of the Week,Maximum Delay,Arrival Delay of Last Stop (min),Nr. of Planned Stops,Nr. of Cancelled Arrivals,Nr. of Cancelled Departures,Nr. of Delayed Arrivals,Nr. of Delayed Departures,Partly Cancelled,Completely Cancelled,Last Arrival Cancelled,Statistical Causes,Disruption Count
2158,[10371450],Leeuwarden - Zwolle,2023-01-01,Sunday,1,1.0,6,0,0,1,1,False,False,False,[an animal on the railway track],1.0
2344,[10371789],'s-Hertogenbosch - Nijmegen,2023-01-02,Monday,2,1.0,8,0,0,7,6,False,False,False,[broken down train],1.0
2345,[10371792],'s-Hertogenbosch - Utrecht Centraal,2023-01-02,Monday,1,0.0,7,0,0,2,2,False,False,False,[broken down train],1.0
2363,[10371819],Breda - Dordrecht,2023-01-02,Monday,1,1.0,3,0,0,2,2,False,False,False,[broken down train],1.0
2395,[10371867],Baarn - Utrecht Centraal,2023-01-02,Monday,1,0.0,6,0,0,1,1,False,False,False,[signal and level crossing failure],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433437,[12646013],Roosendaal - Vlissingen,2023-12-20,Wednesday,0,0.0,9,0,0,0,0,False,False,False,[repair works],1.0
1433438,[12646014],Roosendaal - Vlissingen,2023-12-20,Wednesday,0,0.0,9,0,0,0,0,False,False,False,[repair works],1.0
1433439,[12646015],Roosendaal - Vlissingen,2023-12-20,Wednesday,0,0.0,9,0,0,0,0,False,False,False,[repair works],1.0
1435937,[12649950],Leiden Centraal - Utrecht Centraal,2023-12-21,Thursday,2,2.0,7,3,3,4,3,True,False,False,[broken down train],1.0
1439058,[12654485],Den Haag HS - Rotterdam Centraal,2023-12-21,Thursday,0,0.0,2,0,0,0,0,False,False,False,[points failure],1.0

In [42]:
# Sort the merged_data by 'Disruption Count' in descending order and select the top 10 rows
top_10_disruptions = merged_data.sort_values(by='Disruption Count', ascending=False).head(10)
top_10_disruptions

,RDT-ID,Trajectory,Date,Day of the Week,Maximum Delay,Arrival Delay of Last Stop (min),Nr. of Planned Stops,Nr. of Cancelled Arrivals,Nr. of Cancelled Departures,Nr. of Delayed Arrivals,Nr. of Delayed Departures,Partly Cancelled,Completely Cancelled,Last Arrival Cancelled,Statistical Causes,Disruption Count
722258,[11525022],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,0,0.0,13,14,14,0,0,True,True,True,"[the expected weather conditions, weather circ...",7.0
722659,[11525686],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,5,0.0,13,9,9,3,3,True,False,True,"[the expected weather conditions, weather circ...",7.0
722398,[11525258],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,4,0.0,13,9,9,3,3,True,False,True,"[the expected weather conditions, weather circ...",7.0
719118,[11519724],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,1,0.0,13,0,0,2,1,False,False,False,"[the expected weather conditions, weather circ...",7.0
722541,[11525491],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,10,0.0,13,9,9,5,5,True,False,True,"[the expected weather conditions, weather circ...",7.0
719221,[11519880],Alkmaar - Amsterdam Centraal,2023-07-05,Wednesday,0,0.0,13,0,0,0,0,False,False,False,"[the expected weather conditions, weather circ...",7.0
730808,[11538951],Amsterdam Centraal - Haarlem,2023-07-07,Friday,1,0.0,3,0,0,2,2,False,False,False,"[damaged railway bridge, power failure, power ...",5.0
730786,[11538919],Amsterdam Centraal - Haarlem,2023-07-07,Friday,1,0.0,3,0,0,1,1,False,False,False,"[damaged railway bridge, power failure, power ...",5.0
701301,[11489415],Amsterdam Centraal - Haarlem,2023-06-29,Thursday,0,0.0,3,4,4,0,0,True,True,True,"[disruption elsewhere, power failure, power fa...",4.0
1066117,[12063267],Amsterdam Centraal - Utrecht Centraal,2023-09-25,Monday,5,0.0,9,0,0,9,10,False,False,False,"[points failure, defective railway track, repa...",4.0